# Generated by Django 3.0.6 on 2020-07-27 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Expenditure_Name', models.CharField(max_length=25, null=True)),
                ('Payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('dd', 'dd')], max_length=25, null=True)),
                ('Amount', models.CharField(max_length=50, null=True)),
                ('Date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25, null=True)),
                ('last_name', models.CharField(max_length=50, null=True)),
                ('mobile', models.CharField(max_length=10, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('standard', models.CharField(max_length=10, null=True)),
                ('divison', models.CharField(max_length=10, null=True)),
                ('fee_per_month', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=25, null=True)),
                ('lname', models.CharField(max_length=25, null=True)),
                ('sub', models.CharField(max_length=20, null=True)),
                ('qual', models.CharField(max_length=50, null=True)),
                ('join_date', models.DateField()),
                ('Add', models.CharField(max_length=250, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('active', models.CharField(choices=[('Active', 'Active'), ('Not Active', 'Not Active')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('dd', 'dd')], max_length=10, null=True)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('Teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.Teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student_fee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('dd', 'dd')], max_length=10, null=True)),
                ('amount', models.IntegerField()),
                ('date', models.DateField()),
                ('Student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='login.Students')),
            ],
        ),
    ]
