# Generated by Django 3.0.6 on 2020-07-27 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_fee',
            name='total_fee',
            field=models.IntegerField(default=0),
        ),
    ]
