# Generated by Django 3.0.6 on 2020-07-28 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_student_fee_total_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_fee',
            name='total_fee',
        ),
    ]
